version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: es-abstract
    versions:
    - 1.18.0-next.2
    - 1.18.0-next.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
