on_push: &on_push
  when:
    event:
      - push

kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: bump
    image: node:lts
    <<: *on_push
    commands:
      - git config --global user.name "Drone CI"
      - git config --global user.email buildbot@ci.caseywebb.xyz
      - npm version patch

  - name: push
    image: appleboy/drone-git-push
    <<: *on_push
    settings:
      remote_name: origin
      follow_tags: true
      key:
        from_secret: GIT_SSH_KEY

  - name: publish
    image: plugins/npm
    when:
      event:
        - tag
    settings:
      token:
        from_secret: NPM_TOKEN

---
kind: secret
name: NPM_TOKEN
data: Yy4txZ8nNaIirwbldt0l8P1vJjo/Tv6NWuqBjx6oXsROA2HjKxxLHCEHSkrCfjmxhHzjGr8ebsv5gdw3RPztbQ==

---
kind: secret
name: GIT_SSH_KEY
data: aTtvluVfAknVMsBNdpSmY2pku7mFBM3TxbRlh4pewHKjsEb/kEHAiYXi/SlJodFQgD6L3e4wj40EMF/plxkYB5dYVAo+WokAB3TPeRerTW5jEqyWHAXzAMYWYqnO6noj2hbgkojhlPYM6uYTNFj+YoUk8MnHnmnCbTHIlFTYNO7Sp5cldg1NGCJUStv8e9qhJtjmiutJxyexFlrIO6lCi6HuXthwC2STCo+0HcDJrXMPV9fNNIpumGbHpd/siG05bHHPmSPVjO2nyH5Kp1AeUBlVBN0nfB9kJQZsxXOUJynJ4XKaVu6iFtiuz7xUsReFE0CIyXwtnWhv4FCo4kOJ9bELfgZNeeOaiE8SgkgdeBmKDnd5ocgpd23eeYavoJJ6Sz52qosq7jUYAyFBJUjk1GQB9vISzQ++6B0bqaoltOsbZjuH4REriwUqmAqxDSBYtXlPjtg2cQOyg7o8aR5AGktK5G0LP4eVTTGl16b/uCFwhvsf/hBtn0lPwdOhOLgQR2eA9lRYYAM9djHF4agp96k3X5wK4ob54eZcOAQfy2/U9+tvvoSTV2SOT2mUPtmvrTs1z/VtyYcYbDKkUSrXIN6qO8T+BhITWngassQOi46g6s1hiCTuF8/3dTVkUqoymgdbNmnKQmy1s6uCPhi8/zZdCG/rGEDxIwrvyhJ7Qn/hxdX/bA+TLO2eNmXDvOjVV3ECKY9BffBN7enfuDeF3S9LKlAdvzgtC0vKi/hkaYuUj37tO6njJJkrPC7hrBy5qnG1Rm3M+BAHFGen8/kZ94ZYXFaqlrpKPSmjIBiGH19550P4ndGjthdoye/qAh1DNhZ9nfuqXOcByKS9dFYBipjyxf0RVknFEaaUwfJIu/GcvJL7O5GHj2slKKLBc44QCUDplkV/L19CpyKGEKGlp2DL97c+k+uRhLNYDUWqLO+3QMKO32tHQ1wrxdDU1VLU4kaFGuZr4GQIYxePW+g1zbXtm/lxzPmtY5MAHPxUGubp2WLgwfPmgzQ3P6oB435vot3btv0ntigz+8dhH63ucQuyfZjKe4gk1qnVhfhovxHscJ6ihAseAovOMjMUBi3ZL5mbEl4ZAXUx3YHSwZeq0Hxt+KjHSnAUzf87M/Kmfh5MliCc5C9h+imZYQx57/85gGO551xpXJYW45reKlot5rSq3xfpsahT6C5YYJcSpKvn4JQlMlCPtkFJNPlP1kKtHjF4ZIjWXhz0jRgLWCM0M3mi3KqM5q/LyuNx71Xc5YjjQsILtFE7ViIA96usgVwIdoGaBj5+yyjt9AmTjbCYltB0C1zj3Ae+Xl7vNKuFKXKGG7umHU6aUpL8oIOpqVUl8F605njx3qDDvnmuKEFtdsTOGO9glnd4sBsRUgFEZE8/lkgsko38KKgT7JZZcDxC9er126KY1jQIxTlFhgTXOGneO3ZqYarPS3yT9Q2q1nmhqq9Rrpsoe2PYlSkEpSxr89+/LOEpg7n2Gk0wAvgEh9c0Ak6aPxoOmuiL/bc56Z5LqWqY6LOjVtXd5zORS17QJZFlZWHI8Mak1G+jS9supbS2tc3q702ZjmOZGQ2ids2UUmVppdXaMgrzx+qDHAzjUD8FonRj6mRTfxfbBjVRwQb3aH/Pvv5nxm4BjauqIG7lV9u72l8Z8zVj+qHp63RtpODYbSO/tUvtDHsXoDIqzzMEUUnq4zLh1/dj1KU3SsVXNsh8ttGaXOMRMz2tSkt0vPgVCEa9s4hlmf3qE+wgvvpSVFvHmRYZcN1mHod/dvFFPCgTK5mJiZVIET6OUKF8hk6M4a4Xy+GGJBJ/M4/UhVq0ZFrsjWw6uGzF9pIhr+yW2YM2L203dFyGcqXlB1sIhrDIxZmUogqm4GrF5naYcV1XRzoSCq2GhX9u5ddo+tV2j+f3S5JeWlh5/gbFkFd23tahi0SUfsnjY65DPMBNgnOCRkRLL+v5//cJ8LyJW0mrvKmiorOzJ+tx7S623ijSjV7XfNOGlB47OcPLte++kKIFVzXPJbOplNMzAJPv/M61gjoMY9EhHldxcUXuWncx1jn0eulMHHYkTH02jY0O7Wmc68eV3iAqZ1lb1tcHNbJM86Q4F+P9W61UTdnpH6tguMFTqJ6OUxxweoD5civWfpuv1o2biOSNnf2xBiS59LiZ/JPLJAI1VLxe6XKvSM+vrx1a9m0Q5+lzPBKe5lKEQNivQaibulL7TS5M5uB4df/72hIAmgKnW052yfLft7INPAjyJUINz2nISSWgd1DC2zC0ZzFKMwJtAPhpZMLGSuA8ah0nACnlqoq2yEKStjU3HFhCHd5AbOvVszQJJayCSSHBcBLst0gHSdKoiQlF6/jayjk4XQAdIlftzdGd3k0JSgHt7ig7W6c7tHYoz6QWWDHQWYHc3xHFsu/L602oUPqCbc4/k/3rCev9N5HdjzEVAglTAz+nky1IaRUskxlhesMYay+D+YVDKvTwGs0kMqC7vkpDz2Yji5qUKoWzLbo41C+Fk/y4HA6n0zR7035PYdXgRwVx2/s77+gN7YPKBeWWffoKUdfTFwUXRZNPqzAnbP9RWSp6otnVWbBug7oLdabE4AsmJ3Vw2UbgAdSa+G8KbBJ6HnIuWBcBXCDTUHisT0hRJn0KGKrSWEA2C5pSYuoOGYwf6YHl207MqVp7JjLC2x3MaqX1J0cmu676V4rV+GGimBYZvi+u+va5TLWvzqRNAV2BrdcEsidBfXQRO1iOVxHSl2/iqZ44yKc6eeB2sdLBVRBgOhXyLwOo5XPgJu2RXQd94SSwuARgFcx4MO5ZhyjC/wwjxTd5oBz/TgLyL+xnCyDULLSJx2bKfuWD8u+KMNHIf/Xcz0jM2vnr8PD5cab2CMoCyVrp9F/8/FNs8fCipYLQZfI5R4CtfZDxseptAcs1gFUJn8/yX9+/Ox0QLtMVGNsZyrNTd9qfpohEP+5hN1f0mC+HBxHvxYw/jntDTNz1eoDeuO3oB/es28TER0HuDMfwovFeIXzN6KZlx2gUMTkvoJwLJIWM4RzQ5Nj/o72nqP/ueDoAtAAlLme33b4DBsATx/TSpBA6XSngYxkyNuU2AMX119ieR3R7xLQqeGOy96RNqUKW1cfGr7IBnLe6EgSW8W2aHNNHOWqj4L3dkF/rd4xPQ/jG73gQiV/bXjcs6XAhiUVq5ljCkU1gWl1jUjMBfgeLvZHay4jUzw4lKCINz6Xj4RnQdLA7sPv5gWIdU4RWqJufJCyOYDOctJbdvnGUzYpYVm5KlFtGJQ/OdFAemut/TKi/C9YV2qwLoynHZB1mgeMh6yWi3MiIW8NyScmT9ODh0YjAy27lANaHGQqOy5eJm/vaZbG4VFllTgFXxrL/V/CD7g==
