kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: bump
    image: node:lts
    when:
      event:
        - push
    commands:
      - npm version patch
      - git push --tags

  - name: publish
    image: plugins/npm
    when:
      event:
        - tag
    settings:
      token:
        from_secret: NPM_TOKEN

---
kind: secret
name: NPM_TOKEN
data: Yy4txZ8nNaIirwbldt0l8P1vJjo/Tv6NWuqBjx6oXsROA2HjKxxLHCEHSkrCfjmxhHzjGr8ebsv5gdw3RPztbQ==
