on_push: &on_push
  when:
    event:
      - push

kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: bump
    image: node:lts
    <<: *on_push
    environment:
      GIT_SSH_KEY:
        from_secret: GIT_SSH_PUSH_KEY
    commands:
      - mkdir ~/.ssh
      - echo "$$GIT_SSH_KEY" > ~/.ssh/id_rsa
      - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
      - chmod -R 600 ~/.ssh
      - git config --global user.name "Drone CI"
      - git config --global user.email buildbot@ci.caseywebb.xyz
      - git remote set-url origin git@github.com:Profiscience/eslint-config-profiscience.git
      - npm version patch
      - git push --follow-tags origin master

  - name: publish
    image: plugins/npm
    when:
      event:
        - tag
    settings:
      token:
        from_secret: NPM_TOKEN

---
kind: secret
name: NPM_TOKEN
data: Yy4txZ8nNaIirwbldt0l8P1vJjo/Tv6NWuqBjx6oXsROA2HjKxxLHCEHSkrCfjmxhHzjGr8ebsv5gdw3RPztbQ==
