on_push: &on_push
  when:
    event:
      - push

kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: bump
    image: node:lts
    <<: *on_push
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: GIT_PUSH_SSH_KEY
    commands:
      - mkdir ~/.ssh
      - echo $$GIT_PUSH_SSH_KEY >> ~/.ssh/id_rsa
      - git config --global user.name "Drone CI"
      - git config --global user.email buildbot@ci.caseywebb.xyz
      - git remote set-url origin git@github.com:Profiscience/eslint-config-profiscience.git
      - npm version patch
      - git push --follow-tags

  - name: publish
    image: plugins/npm
    when:
      event:
        - tag
    settings:
      token:
        from_secret: NPM_TOKEN

---
kind: secret
name: NPM_TOKEN
data: Yy4txZ8nNaIirwbldt0l8P1vJjo/Tv6NWuqBjx6oXsROA2HjKxxLHCEHSkrCfjmxhHzjGr8ebsv5gdw3RPztbQ==
